### ISSUE TITLE
May 1: Go-live checklist

### ISSUE THREAD

**Issue by gaurav-naik** [mntechnique/kisanmitra_erpnext#15]
- [x] Popups not showing (Critical).
- [x] Cannot search phone number on CRM dashboard.
- [ ] Department officials should (ideally) see issues by department.
- [ ] Explore whether more fields can be added in list search.
- [x] Multiple duplicate communications being created.

**Comment by gaurav-naik** [comment]
Addressed in #37 #38 #39
