### ISSUE TITLE
Go-live: Part 1 : Checklist : Access to officials

### ISSUE THREAD

**Issue by nanoharsha** [mntechnique/kisanmitra_erpnext#16]
**Must : Data Import:** 
- [x] Import Status Data from Data Dump, and map it in ERPNext accordingly as attached below
[Status_Mapping_ERPNExt_Vtiger.pdf](https://github.com/mntechnique/kisanmitra_erpnext/files/1968353/Status_Mapping_ERPNExt_Vtiger.pdf)
.
**Optional and could be handled from Front End if not Feasible or  worst condition "Let the users figure out" :** 

- [ ] Visibility of Fields : We need to show only a few fields to officials so that they could open and quickly respond and get back to their other work. We have captured these fields in our PDF reports which are reviewed physical every week by the Dist. Administration. and is as attached.
[All_Depts_Except_Rural_Dev.pdf](https://github.com/mntechnique/kisanmitra_erpnext/files/1968358/All_Depts_Except_Rural_Dev.pdf)

- [ ]  User/Permissions : Filter Data and show only relevant case to officials who would login, based on the Department as well as the Jurisdiction they belong to.
